# Fast Test Configuration for 1000-Node NeuroGraph
# Reduced epochs for quick validation with updated radiation.py

system:
  mode: "modular"
  version: "2.0"
  description: "Fast test - 1000-node NeuroGraph with reduced epochs for validation"

architecture:
  total_nodes: 1000
  input_nodes: 200
  output_nodes: 10
  intermediate_nodes: 790
  vector_dim: 8
  seed: 42

resolution:
  phase_bins: 64
  mag_bins: 1024
  resolution_increase: 16

graph_structure:
  cardinality: 6
  top_k_neighbors: 6
  use_radiation: true

radiation:
  batch_size: 64
  cache_enabled: true

input_processing:
  adapter_type: "linear_projection"
  input_dim: 784
  learnable: true
  normalization: "layer_norm"
  dropout: 0.1

class_encoding:
  type: "orthogonal"
  num_classes: 10
  encoding_dim: 8
  orthogonality_threshold: 0.1

loss_function:
  type: "categorical_crossentropy"
  temperature: 1.0
  label_smoothing: 0.0

training:
  gradient_accumulation:
    enabled: true
    accumulation_steps: 8
    lr_scaling: "sqrt"
    buffer_size: 1000
  
  optimizer:
    type: "discrete_sgd"
    base_learning_rate: 0.01
    warmup_epochs: 10     # Balanced for production training
    num_epochs: 30        # Production training epochs
    batch_size: 5
  
  quick_mode:
    epochs: 5
    warmup_epochs: 2

forward_pass:
  max_timesteps: 35
  decay_factor: 0.925
  min_activation_strength: 0.01
  min_output_activation_timesteps: 3

activation_balancing:
  enabled: true
  strategy: "round_robin"
  max_activations_per_epoch: 20
  min_activations_per_epoch: 5
  force_activation_probability: 0.5

multi_output_loss:
  enabled: true
  continue_timesteps_after_first: 3
  max_outputs_to_train: 4

paths:
  graph_path: "config/modular_static_graph.pkl"
  log_path: "logs/modular/"
  checkpoint_path: "checkpoints/modular/"
  training_curves_path: "logs/modular/training_curves.png"

fallback:
  enable_legacy_mode: true
  legacy_config_path: "config/default.yaml"
  auto_fallback_on_error: true

debugging:
  verbose_logging: false
  save_intermediate_states: false
  plot_training_curves: true
  evaluation_samples: 300
  final_evaluation_samples: 500
